name: Build website PR

on:
  pull_request:
    branches:
      - "main"
    types:
      - closed

concurrency:
  group: "builders"
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          make install
      - name: Build website
        run: make website
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Built website"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
